#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


PATH=$HOME/Documents/android-sdk-linux/tools:/usr/local/bin:/usr/local/sbin:$PATH
export PATH

alias l='ls -lah'
alias g='git'
alias p="cd ~/Documents/Projects/"
alias m='mate'
alias clean_pyc='find . -name \*.pyc -delete'
alias clean_orig='find . -name \*.orig -delete'
alias clean_tilde='find . -name \*~ -delete'

if hash nvim 2>/dev/null; then
	alias v='nvim'
else
	alias v='vim'
fi

if [[ -s "/usr/local/share/python/virtualenvwrapper.sh" ]]; then
    source /usr/local/share/python/virtualenvwrapper.sh
fi

if [[ -s "/usr/share/virtualenvwrapper/virtualenvwrapper.sh" ]]; then
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
fi

if [[ -s "/usr/local/opt/autoenv/activate.sh" ]]; then
    source /usr/local/opt/autoenv/activate.sh
fi

# sourcing autoenv when pip installing it on ubuntu...
if [[ -s "/usr/local/bin/activate.sh" ]]; then
    source /usr/local/bin/activate.sh
fi

zstyle -e ':completion:*:hosts' hosts 'reply=(
    ${=${${${${(@M)${(f)"$(cat ~/.ssh/config 2>/dev/null)"}:#Host *}#Host }:#*\**}:#*\?*}}
)'
zstyle ':completion:*:ssh:*' tag-order 'hosts:-host:host hosts:-domain:domain hosts:-ipaddr:ip\ address *'
zstyle ':completion:*:ssh:*' group-order hosts-host hosts-domain hosts-ipaddr
